config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path("", include("djsniper.sniper.urls", namespace="sniper")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("djsniper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djsniper/sniper/urls.py
from django.urls import path, include
from . import views

app_name = "sniper"

urlpatterns = [
    path("", views.HomeCategoriesListView.as_view(), name="home"),
    path("projects/", views.ProjectListView.as_view(), name="projects"),
    path("create/", views.ProjectCreateView.as_view(), name="project-create"),
    path("project/<pk>/", views.ProjectDetailView.as_view(), name="project-detail"),
    path(
        "project/<pk>/update/", views.ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "project/<pk>/delete/", views.ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/<pk>/clear/", views.ProjectClearView.as_view(), name="project-clear"),
    path("project/<pk>/fetch-nfts/", views.FetchNFTsView.as_view(), name="fetch-nfts"),
    #path("project/<pk>/order/", views.ProjectDetailView.as_view(), name="order"),},
    path("my-projects/<str:username>/", views.UserProjectsView.as_view(), name="my-projects"),
    path("my-payments/<str:username>/", views.UserPaymentsHistoryView.as_view(), name="my-payments"),
    path("my-billings/<str:username>/", views.UserBillingsView.as_view(), name="my-billings"),
    path("add-voucher/<pk>/", views.OrderUpdateView.as_view(), name="add-voucher"),
    path("show-voucher/<pk>/", views.VoucherDetailView.as_view(), name="show-voucher"),
    path("choose/", views.ChooseRole, name="choose")

]

djsniper/users/urls.py
from django.urls import path

from djsniper.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    UserPersonalCreateView,
    UserEnterpriseCreateView,
    OrderCreateView,
    UserProfileView,
    user_password_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>", view=user_detail_view, name="detail"),
    path("profile/<str:username>", view=UserProfileView, name="profile"),
    path("personal/", view=UserPersonalCreateView.as_view, name="personal"),
    path("enterprise/", view=UserEnterpriseCreateView.as_view(), name="enterprise"),
    path("password/<str:username>", view=user_password_view, name="password")
]

djsniper/sniper/forms.py
from django import forms
from .models import NFTProject, Category


class ProjectForm(forms.ModelForm):
    class Meta:
        model = NFTProject
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ConfirmForm(forms.Form):
    hidden = forms.HiddenInput()

djsniper/sniper/api/views.py
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.viewsets import GenericViewSet
from djsniper.sniper.models import NFTProject
from .serializers import NFTProjectSerializer, CategorySerializer


class ProjectViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = NFTProjectSerializer
    queryset = NFTProject.objects.all()
    lookup_field = "name"


class CategoryViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = CategorySerializer
    queryset = CategorySerializer.objects.all()
    lookup_field = "name"

djsniper/sniper/views.py
import json
import sys
from operator import attrgetter

from celery.result import AsyncResult
from django.http import Http404, HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.detail import SingleObjectMixin, View
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from djsniper.sniper.forms import ConfirmForm, ProjectForm
from djsniper.sniper.models import NFTAttribute, NFTProject, Category
from djsniper.sniper.tasks import fetch_nfts_task
from rest_framework import viewsets
from djsniper.sniper.api import serializers
from djsniper.users.forms import OrderCreationForm, OrderUpdateForm
from djsniper.users.models import Order, User
from django.views.generic.edit import ModelFormMixin
from djsniper.users.api.serializers import OrderSerializer
from itertools import groupby

sys.setrecursionlimit(10000)


class HomeCategoriesListView(generic.ListView):
    template_name = "base.html"

    def get_queryset(self):
        return Category.objects.all()


def ChooseRole(request):
    return render(request, "account/choose_role.html")


class ProjectViewset(viewsets.ModelViewSet):
    queryset = NFTProject.objects.all()
    serializer_class = serializers.NFTProjectSerializer

    def get_queryset(self):
        project = NFTProject.objects.all()

        name = self.request.GET.get('name')

        if name:

            project = project.filter(name__contains=name)

        else:

            return project


class CategoryViewset(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = serializers.CategorySerializer

    def get_queryset(self):
        category = Category.objects.all()

        name = self.request.GET.get('name')

        if name:

            category = category.filter(name__contains=name)

        else:

            return category

class OrdersViewset(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = serializers.OrderSerializer

    def get_queryset(self):
        category = Category.objects.all()

        #name = self.request.GET.get('name')
        #if name:
        #    category = category.filter(name__contains=name)
        #else:
        #    return category

class ProjectListView(generic.ListView):
    template_name = "sniper/project_list.html"

    def get_queryset(self):
        return NFTProject.objects.all()


class UserProjectsView(generic.ListView):
    template_name = "users/my_projects.html"

    #def get_queryset(self):
    #    objects = Order.objects.all()

    #    grouped_objects = groupby(objects.values('nft'))
    #    print(grouped_objects, lambda x: x['id'])
    #    return {'grouped_objects': grouped_objects}
    #     return Order.objects.filter(approved=True)
    model = Order

    def __init__(self):
        self.orders = Order.objects.all()

    def group_by_project(self):
        grouped_orders = {}
        for order in self.orders:
            if order.nft not in grouped_orders:
                grouped_orders[order.nft] = []
            grouped_orders[order.nft].append(order)
        return print(grouped_orders)

    def filter_by_approval(self, approved=True):
        filtered_orders = []
        for order in self.orders:
            if order.approved == approved:
                filtered_orders.append(order)
                grouped_objects = filtered_orders
        return print(grouped_objects)


class UserBillingsView(generic.ListView):
    template_name = "users/billings.html"

    def get_queryset(self):
        return Order.objects.all()


class UserPaymentsHistoryView(generic.ListView):
    template_name = "users/payments_history.html"

    def get_queryset(self):
        return Order.objects.all()


# class ProjectDetailView(generic.DetailView):
#    template_name = "sniper/project_detail.html"

#    def get_queryset(self):
#        return NFTProject.objects.all()

#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        nft_project = self.get_object()
#        order = self.request.GET.get("order", None)
#        nfts = nft_project.nfts.all()
#        if order == "rank":
#            nfts = nfts.order_by("rank")
#        context.update({"nfts": nfts[0:12]})
#        return context

# class ProjectDetailView(FormMixin, generic.DetailView):

#    model = Order
#    context_object_name = 'object'
#    template_name = 'sniper/order_create.html'
#    form_class = OrderCreationForm

#    def get_success_url(self):
#        return reverse('project-detail', kwargs={'pk': self.object.pk})
#        #return reverse('sniper:home')

#    def get_object(self):
#        try:
#            my_object = NFTProject.objects.get(id=self.kwargs.get('pk'))
#            return my_object
#        except self.model.DoesNotExist:
#            raise Http404("No MyModel matches the given query.")

#    def get_context_data(self, *args, **kwargs):
#        context = super(ProjectDetailView, self).get_context_data(*args, **kwargs)
#        nft_project = self.get_object()
# form
#        context['form'] = self.get_form()
#        context['project'] = nft_project
#        return context

#    def post(self, request, *args, **kwargs):
#        self.object = self.get_object()
#        form = self.get_form()
#        if form.is_valid():
#            return self.form_valid(form)
#        else:
#            return self.form_invalid(form)

#    def form_valid(self, form):
# put logic here
#        return super(ProjectDetailView, self).form_valid(form)

#    def form_invalid(self, form):
# put logic here
#        return super(ProjectDetailView, self).form_invalid(form)


# class ProjectDetailView(generic.DetailView):
#    template_name = "sniper/project_detail.html"

#    def get_queryset(self):
#        return NFTProject.objects.all()

#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        nft_project = self.get_object()
#        order = self.request.GET.get("order", None)
#        nfts = nft_project.nfts.all()
#        if order == "rank":
#            nfts = nfts.order_by("rank")
#        context.update({"nfts": nfts[0:12]})
#        return context

class ProjectDetailView(ModelFormMixin, generic.DetailView):
    model = NFTProject
    template_name = 'sniper/project_detail.html'
    form_class = OrderCreationForm

    # no get_context_data override

    def post(self, request, *args, **kwargs):
        # first construct the form to avoid using it as instance
        form = self.get_form()
        user = request.user
        nft_project = self.get_object()

        if form.is_valid():
            # instance = form.save()
            NFTProject.objects.filter(pk=nft_project.id).update(
                supply=int(int(nft_project.supply) - int(form.cleaned_data["bonuses"])))
            user.project.add(nft_project.id)
            # form.cleaned_data["purchase"] = nft_project.price * form.cleaned_data["bonuses"]
            # form = nft_project.price * form.cleaned_data["bonuses"]
            # instance = form.save()
            # updateProjectSupply(project, instance.bonuses)
            print(form)
            instance = form.save()
            Order.objects.filter(pk=instance.id).update(
                purchase=int(int(nft_project.price) * int(form.cleaned_data["bonuses"])))
            return redirect("sniper:home")
        else:
            print(form)
            return super(ProjectDetailView, self.get_object()).form_invalid(form)

            # return form

    def get_success_url(self):
        return redirect("sniper:home")


class OrderCreateView(generic.CreateView):
    template_name = "sniper/order_create.html"
    form_class = OrderCreationForm
    model = NFTProject

    def form_valid(self, form):
        # instance = form.save()
        # nft_project = self.get_object()
        # NFTProject.objects.filter(pk=nft_project.id).update(supply=('supply') - instance.bonuses)
        # instance = form.save()
        # updateProjectSupply(project, instance.bonuses)
        return redirect("sniper:home")

    def get_queryset(self):
        return Order.objects.all()


class ProjectCreateView(generic.CreateView):
    template_name = "sniper/project_create.html"
    form_class = ProjectForm

    def form_valid(self, form):
        instance = form.save()
        return redirect("sniper:project-detail", pk=instance.id)

    def get_queryset(self):
        return NFTProject.objects.all()


class ProjectUpdateView(generic.UpdateView):
    template_name = "sniper/project_update.html"
    form_class = ProjectForm

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-detail", kwargs={"pk": self.get_object().id})


class OrderUpdateView(generic.UpdateView):
    template_name = "users/add_voucher.html"
    form_class = OrderUpdateForm

    def get_queryset(self):
        return Order.objects.all()

    def get_success_url(self):
        return reverse("sniper:home")  # , kwargs={"username": self.get_object().id})


class VoucherDetailView(generic.DetailView):
    template_name = "users/show_voucher.html"

    def get_queryset(self):
        return Order.objects.all()


class ProjectDeleteView(generic.DeleteView):
    template_name = "sniper/project_delete.html"

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-list")


class ProjectClearView(SingleObjectMixin, generic.FormView):
    template_name = "sniper/project_clear.html"
    form_class = ConfirmForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

djsniper/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

djsniper/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en" class="h-full">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Gaya Live{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Django Self-Hosted NFT Rarity Sniper">
  <meta name="author" content="Matthew Freire">

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  <!--<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  {% block css %}
  <!-- Your stuff: Third-party CSS libraries go here -->
  <!-- This file stores project-specific CSS -->
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
    ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
  <!-- place project specific Javascript in this file -->
  <script defer src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}

</head>

<body class="h-full" style="">

  <div class="min-h-full">
    <nav class="bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex" style="display:flex; flex-direction:row; justify-content:center;">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 bg-white p-6" style="width:70vw;">

              <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
              <img src="{% static 'images/general/logogaya.jpg' %}" style="width:40px; height:40px;"/>&nbsp; &nbsp;
               <span class="text-success">Gaya Live</span>
           </a>
            {% if user.is_authenticated %}
             <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
               <li><a href="{% url 'sniper:projects' %}" class="nav-link px-2 link-dark">Proyecto</a></li>
                <li><a href="{% url 'about' %}" class="nav-link px-2 link-dark">Nosotros</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Contáctanos</a></li>
             </ul>
              <div class="col-md-3 text-end">
                <a href="{% url 'users:detail' user.username %}" class="" style="text-decoration:none;">
                     <img src="{% static 'images/favicons/profileuser.png' %}" style="width:40px; height:40px; margin-right:10px;"/>&nbsp;
                </a>
                <a href="{% url 'account_logout' %}" class="" style="text-decoration:none;">
                    <img src="{% static 'images/favicons/logout.png' %}" style="width:35px; height:35px; margin-right:10px;"/>&nbsp;
                </a>
              </div>
            {% else %}
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'sniper:projects' %}" class="nav-link px-2 link-dark">Proyecto</a></li>
                <li><a href="{% url 'about' %}" class="nav-link px-2 link-dark">Nosotros</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Contáctanos</a></li>
             </ul>
            <div class="col-md-3 text-end">
                <a href="{% url 'account_login' %}" class="btn btn-outline-success me-2">Acceder</a>
                <!--<a  href="{% url 'account_signup' %}" class="btn btn-success">Crear cuenta</a>-->
              <a href="{% url 'sniper:choose' %}" class="btn btn-success"> Crear cuenta</a>
              </div>
            {% endif %}


            </div>
          </div>
          <!--<div class="hidden sm:ml-6 sm:flex sm:items-center">
            -- Profile dropdown --
            <div class="ml-3 relative">

            </div>
          </div>-->

        </div>
      </div>
    </nav>
    <div class="container" style="70vw">
      {% block content %}
       <!-- START THE FEATURETTES -->
      <div class="row featurette" style="vertical-align:middle; margin-bottom: 7rem; margin-top:7rem;">
        <div class="col-md-7 text-center" style="display:flex; flex-direction: column; align-items:center; justify-content:center;">
          <h1 class="featurette-heading fw-bold lh-1">Hoy somos un planeta rojo</h1>
          <button class="btn btn-success mt-5 pt-3 pb-3 p-5">Actuemos ya!</button>
        </div>
        <div class="col-md-5 text-center">
          <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto " width="400" height="400" src="{% static 'images/general/planet.png' %}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"/>

        </div>
      </div>


      <h3 class="text-center fw-bold lh-1 text-success"  style="margin-top:7rem; margin-bottom:7rem;">CONTRIBUIR ES MUY FÁCIL Y SIN COMPLICACIONES</h3>
    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-3 text-center">
          <img src="{% static 'images/general/logogaya.jpg' %}" style="width:80px; height:80px;"/>
          <h4 class="fw-normal">Regístrate</h4>
          <p> Haz parte de nuestra comunidad que vive día a día por un mundo carbono neutral</p>

      </div><!-- /.col-lg-4 -->
      <div class="col-lg-3 text-center">
          <img src="{% static 'images/general/logogaya.jpg' %}" style="width:80px; height:80px;"/>
          <h4 class="fw-normal text-center">Explora</h4>
          <p> Explora los proyectos liderados por los desarrolladores de impacto ambiental positivo</p>

      </div><!-- /.col-lg-4 -->
      <div class="col-lg-3 text-center">
         <img src="{% static 'images/general/logogaya.jpg' %}" style="width:80px; height:80px;"/>
         <h4 class="fw-normal">Contribuye</h4>
         <p>Contribuye a los proyectos de tu interés y comienza a acercarte a tus objetivos de tener un impacto carbono neutral en el planeta</p>

      </div>
      <div class="col-lg-3 text-center">
         <img src="{% static 'images/general/logogaya.jpg' %}" style="width:80px; height:80px;"/>
         <h4 class="fw-normal">Administra</h4>
         <p>Administra y realiza seguimiento a los proyectos de tu portafolio</p>

      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->

     <h3 class="text-center fw-bold lh-1 text-success " style="margin-top:7rem; margin-bottom:7rem;">NAVEGA ENTRE CATEGORÍAS</h3>
     <div class="row">

           <div class="col-lg-3 text-center">
             <div class="card mb-3" style="max-width: 18rem;">
               <div class="text-left text-success pw-bold"><h5>Hidroeléctrica</h5></div>
               <div class="card-body text-success">
                 <img src="{% static 'images/favicons/hydro-power (1).png' %}" style="width:8rem; height:8rem;"/>
               </div>
             </div>
           </div>

          <div class="col-lg-3 text-center">
             <div class="card mb-3" style="max-width: 18rem;">
               <div class="text-left text-success pw-bold"><h5>Nuclear</h5></div>
               <div class="card-body text-success">
                 <img src="{% static 'images/favicons/nuclear-power.png' %}" style="width:8rem; height:8rem;"/>
               </div>
             </div>
           </div>

          <div class="col-lg-3 text-center">
             <div class="card mb-3" style="max-width: 18rem;">
               <div class="text-left text-success pw-bold"><h5>Geotérmica</h5></div>
               <div class="card-body text-success">
                 <img src="{% static 'images/favicons/volcano.png' %}" style="width:8rem; height:8rem;"/>
               </div>
             </div>
           </div>

          <div class="col-lg-3 text-center">
             <div class="card mb-3" style="max-width: 18rem;">
               <div class="text-left text-success pw-bold"><h5>Eólica</h5></div>
               <div class="card-body text-success">
                 <img src="{% static 'images/favicons/wind-turbine.png' %}" style="width:8rem; height:8rem;"/>
               </div>
             </div>
           </div>

    </div>
    <div class="py-10">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}
      <main>
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

        </div>
      </main>
    </div>
      {% endblock  %}
  </div>
{% block footer %}
    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">&copy; 2022 Gaya Live, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
        </ul>
      </footer>
    </div>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

  {% block modal %}{% endblock modal %}

  {% block inline_javascript %}
  {% comment %}
  Script tags with only code, no src (defer by default). To run
  with a "defer" so that you run run inline code:
  <script>
    window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */ });
  </script>
  {% endcomment %}
  {% endblock inline_javascript %}
</body>

</html>

djsniper/templates/nfts.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-3xl font-bold leading-tight text-gray-900">
    Bored Ape Yacht Club
</h1>
<div class="mt-5 grid grid-cols-4 gap-4">
    {% for nft in nfts %}
    <div class="py-3 px-3 border border-gray-200 shadow-sm">
        <img class="w-full rounded-md" src="https://ipfs.io/ipfs/{{ nft.image_url }}" />
        <div class="mt-1">
            <h1 class="text-lg text-gray-800 font-bold">#{{ nft.nft_id }}</h1>
            <p class="text-base text-gray-600">Score: {{ nft.rarity_score|floatformat:2 }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

djsniper/templates/payments.html
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}