config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path("", include("djsniper.sniper.urls", namespace="sniper")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("djsniper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djsniper/sniper/urls.py
from django.urls import path, include
from . import views

app_name = "sniper"

urlpatterns = [
    path("", views.HomeCategoriesListView.as_view(), name="home"),
    path("projects/", views.ProjectListView.as_view(), name="projects"),
    path("create/", views.ProjectCreateView.as_view(), name="project-create"),
    path("project/<pk>/", views.ProjectDetailView.as_view(), name="project-detail"),
    path(
        "project/<pk>/update/", views.ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "project/<pk>/delete/", views.ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/<pk>/clear/", views.ProjectClearView.as_view(), name="project-clear"),
    path("project/<pk>/fetch-nfts/", views.FetchNFTsView.as_view(), name="fetch-nfts"),
    #path("project/<pk>/order/", views.ProjectDetailView.as_view(), name="order"),},
    path("my-projects/<str:username>/", views.UserProjectsView.as_view(), name="my-projects"),
    path("my-payments/<str:username>/", views.UserPaymentsHistoryView.as_view(), name="my-payments"),
    path("my-billings/<str:username>/", views.UserBillingsView.as_view(), name="my-billings"),
    path("add-voucher/<pk>/", views.OrderUpdateView.as_view(), name="add-voucher"),
    path("show-voucher/<pk>/", views.VoucherDetailView.as_view(), name="show-voucher"),
    path("choose/", views.ChooseRole, name="choose")

]

djsniper/users/urls.py
from django.urls import path

from djsniper.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    UserPersonalCreateView,
    UserEnterpriseCreateView,
    OrderCreateView,
    UserProfileView,
    user_password_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>", view=user_detail_view, name="detail"),
    path("profile/<str:username>", view=UserProfileView, name="profile"),
    path("personal/", view=UserPersonalCreateView.as_view, name="personal"),
    path("enterprise/", view=UserEnterpriseCreateView.as_view(), name="enterprise"),
    path("password/<str:username>", view=user_password_view, name="password")
]

djsniper/sniper/forms.py
from django import forms
from .models import NFTProject, Category


class ProjectForm(forms.ModelForm):
    class Meta:
        model = NFTProject
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ConfirmForm(forms.Form):
    hidden = forms.HiddenInput()

djsniper/sniper/api/views.py
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.viewsets import GenericViewSet
from djsniper.sniper.models import NFTProject
from .serializers import NFTProjectSerializer, CategorySerializer


class ProjectViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = NFTProjectSerializer
    queryset = NFTProject.objects.all()
    lookup_field = "name"


class CategoryViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = CategorySerializer
    queryset = CategorySerializer.objects.all()
    lookup_field = "name"

djsniper/sniper/views.py
import json
import sys
from operator import attrgetter

from celery.result import AsyncResult
from django.http import Http404, HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.detail import SingleObjectMixin, View
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from djsniper.sniper.forms import ConfirmForm, ProjectForm
from djsniper.sniper.models import NFTAttribute, NFTProject, Category
from djsniper.sniper.tasks import fetch_nfts_task
from rest_framework import viewsets
from djsniper.sniper.api import serializers
from djsniper.users.forms import OrderCreationForm, OrderUpdateForm
from djsniper.users.models import Order, User
from django.views.generic.edit import ModelFormMixin
from djsniper.users.api.serializers import OrderSerializer
from itertools import groupby

sys.setrecursionlimit(10000)


class HomeCategoriesListView(generic.ListView):
    template_name = "base.html"

    def get_queryset(self):
        return Category.objects.all()


def ChooseRole(request):
    return render(request, "account/choose_role.html")


class ProjectViewset(viewsets.ModelViewSet):
    queryset = NFTProject.objects.all()
    serializer_class = serializers.NFTProjectSerializer

    def get_queryset(self):
        project = NFTProject.objects.all()

        name = self.request.GET.get('name')

        if name:

            project = project.filter(name__contains=name)

        else:

            return project


class CategoryViewset(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = serializers.CategorySerializer

    def get_queryset(self):
        category = Category.objects.all()

        name = self.request.GET.get('name')

        if name:

            category = category.filter(name__contains=name)

        else:

            return category

class OrdersViewset(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = serializers.OrderSerializer

    def get_queryset(self):
        category = Category.objects.all()

        #name = self.request.GET.get('name')
        #if name:
        #    category = category.filter(name__contains=name)
        #else:
        #    return category

class ProjectListView(generic.ListView):
    template_name = "sniper/project_list.html"

    def get_queryset(self):
        return NFTProject.objects.all()


class UserProjectsView(generic.ListView):
    template_name = "users/my_projects.html"

    #def get_queryset(self):
    #    objects = Order.objects.all()

    #    grouped_objects = groupby(objects.values('nft'))
    #    print(grouped_objects, lambda x: x['id'])
    #    return {'grouped_objects': grouped_objects}
    #     return Order.objects.filter(approved=True)
    model = Order

    def __init__(self):
        self.orders = Order.objects.all()

    def group_by_project(self):
        grouped_orders = {}
        for order in self.orders:
            if order.nft not in grouped_orders:
                grouped_orders[order.nft] = []
            grouped_orders[order.nft].append(order)
        return print(grouped_orders)

    def filter_by_approval(self, approved=True):
        filtered_orders = []
        for order in self.orders:
            if order.approved == approved:
                filtered_orders.append(order)
                grouped_objects = filtered_orders
        return print(grouped_objects)


class UserBillingsView(generic.ListView):
    template_name = "users/billings.html"

    def get_queryset(self):
        return Order.objects.all()


class UserPaymentsHistoryView(generic.ListView):
    template_name = "users/payments_history.html"

    def get_queryset(self):
        return Order.objects.all()


# class ProjectDetailView(generic.DetailView):
#    template_name = "sniper/project_detail.html"

#    def get_queryset(self):
#        return NFTProject.objects.all()

#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        nft_project = self.get_object()
#        order = self.request.GET.get("order", None)
#        nfts = nft_project.nfts.all()
#        if order == "rank":
#            nfts = nfts.order_by("rank")
#        context.update({"nfts": nfts[0:12]})
#        return context

# class ProjectDetailView(FormMixin, generic.DetailView):

#    model = Order
#    context_object_name = 'object'
#    template_name = 'sniper/order_create.html'
#    form_class = OrderCreationForm

#    def get_success_url(self):
#        return reverse('project-detail', kwargs={'pk': self.object.pk})
#        #return reverse('sniper:home')

#    def get_object(self):
#        try:
#            my_object = NFTProject.objects.get(id=self.kwargs.get('pk'))
#            return my_object
#        except self.model.DoesNotExist:
#            raise Http404("No MyModel matches the given query.")

#    def get_context_data(self, *args, **kwargs):
#        context = super(ProjectDetailView, self).get_context_data(*args, **kwargs)
#        nft_project = self.get_object()
# form
#        context['form'] = self.get_form()
#        context['project'] = nft_project
#        return context

#    def post(self, request, *args, **kwargs):
#        self.object = self.get_object()
#        form = self.get_form()
#        if form.is_valid():
#            return self.form_valid(form)
#        else:
#            return self.form_invalid(form)

#    def form_valid(self, form):
# put logic here
#        return super(ProjectDetailView, self).form_valid(form)

#    def form_invalid(self, form):
# put logic here
#        return super(ProjectDetailView, self).form_invalid(form)


# class ProjectDetailView(generic.DetailView):
#    template_name = "sniper/project_detail.html"

#    def get_queryset(self):
#        return NFTProject.objects.all()

#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        nft_project = self.get_object()
#        order = self.request.GET.get("order", None)
#        nfts = nft_project.nfts.all()
#        if order == "rank":
#            nfts = nfts.order_by("rank")
#        context.update({"nfts": nfts[0:12]})
#        return context

class ProjectDetailView(ModelFormMixin, generic.DetailView):
    model = NFTProject
    template_name = 'sniper/project_detail.html'
    form_class = OrderCreationForm

    # no get_context_data override

    def post(self, request, *args, **kwargs):
        # first construct the form to avoid using it as instance
        form = self.get_form()
        user = request.user
        nft_project = self.get_object()

        if form.is_valid():
            # instance = form.save()
            NFTProject.objects.filter(pk=nft_project.id).update(
                supply=int(int(nft_project.supply) - int(form.cleaned_data["bonuses"])))
            user.project.add(nft_project.id)
            # form.cleaned_data["purchase"] = nft_project.price * form.cleaned_data["bonuses"]
            # form = nft_project.price * form.cleaned_data["bonuses"]
            # instance = form.save()
            # updateProjectSupply(project, instance.bonuses)
            print(form)
            instance = form.save()
            Order.objects.filter(pk=instance.id).update(
                purchase=int(int(nft_project.price) * int(form.cleaned_data["bonuses"])))
            return redirect("sniper:home")
        else:
            print(form)
            return super(ProjectDetailView, self.get_object()).form_invalid(form)

            # return form

    def get_success_url(self):
        return redirect("sniper:home")


class OrderCreateView(generic.CreateView):
    template_name = "sniper/order_create.html"
    form_class = OrderCreationForm
    model = NFTProject

    def form_valid(self, form):
        # instance = form.save()
        # nft_project = self.get_object()
        # NFTProject.objects.filter(pk=nft_project.id).update(supply=('supply') - instance.bonuses)
        # instance = form.save()
        # updateProjectSupply(project, instance.bonuses)
        return redirect("sniper:home")

    def get_queryset(self):
        return Order.objects.all()


class ProjectCreateView(generic.CreateView):
    template_name = "sniper/project_create.html"
    form_class = ProjectForm

    def form_valid(self, form):
        instance = form.save()
        return redirect("sniper:project-detail", pk=instance.id)

    def get_queryset(self):
        return NFTProject.objects.all()


class ProjectUpdateView(generic.UpdateView):
    template_name = "sniper/project_update.html"
    form_class = ProjectForm

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-detail", kwargs={"pk": self.get_object().id})


class OrderUpdateView(generic.UpdateView):
    template_name = "users/add_voucher.html"
    form_class = OrderUpdateForm

    def get_queryset(self):
        return Order.objects.all()

    def get_success_url(self):
        return reverse("sniper:home")  # , kwargs={"username": self.get_object().id})


class VoucherDetailView(generic.DetailView):
    template_name = "users/show_voucher.html"

    def get_queryset(self):
        return Order.objects.all()


class ProjectDeleteView(generic.DeleteView):
    template_name = "sniper/project_delete.html"

    def get_queryset(self):
        return NFTProject.objects.all()

    def get_success_url(self):
        return reverse("sniper:project-list")


class ProjectClearView(SingleObjectMixin, generic.FormView):
    template_name = "sniper/project_clear.html"
    form_class = ConfirmForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

djsniper/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

djsniper/templates/users/dashboard.html
{% extends "base.html" %}
{% load i18n %}

{% load crispy_forms_tags %}

{% block head_title %}{% translate "Signup" %}{% endblock %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/product-card.css' %}">
{% endblock %}

{% load humanize %}
{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<!--<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
-- Action buttons --
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    -- Your Stuff: Custom user template urls --
  </div>

</div>
-- End Action buttons --
{% endif %}

</div>-->
  <section style="">
    <div class="container py-3">
      <div class="row">
        <!--<div class="col">
          <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
            <ol class="breadcrumb mb-0">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
        </div>-->
      </div>

      <div class="row">
        <div class="col-lg-3">
          <div class="card mb-4">
            <div class="card-body text-left">
              <!--<h5 class="my-3 text-capitalize">{{ object.username }}</h5>
              <p class="text-muted mb-1">{{ object.role }}</p>
              <p class="text-muted mb-4">{{ object.email }}</p>-->
              <!--{% if object.role == "Empresa" %}-->
              <!--{% elif object.role == "Persona Natural" %}-->
              <!--{% endif %}--->
              <div class="d-flex align-left mb-2">
                  <a  href="{% url 'sniper:my-projects' user.username %}" type="button" class="btn btn-light w-100 fw-bold align-center">
                    <img src="{% static 'images/dashboard/icons/wave.png' %}" style="width:30px; height:30px; margin-right: 3rem;" class="mr-2"/>
                    Proyectos
                  </a>
              </div>
              <div class="d-flex justify-content-left mb-2">
                  <button type="button" class="btn btn-light w-100 fw-bold p-3 text-left">
                    <img src="{% static 'images/dashboard/icons/wallet.png' %}" style="width:30px; height:30px; margin-right: 1rem;"/>
                    Conectar wallet
                  </button>
              </div>
              <div class="d-flex justify-content-left mb-2">
                  <a href="#" type="button" class="btn btn-light w-100 fw-bold p-3 text-left">
                    <img src="{% static 'images/dashboard/icons/usericon.png' %}" style="width:30px; height:30px; margin-right: 5rem;"/>
                    Perfil
                  </a>
              </div>
              <div class="d-flex justify-content-left mb-2">
                  <a href="{% url 'sniper:my-billings' user.username %}" type="button" class="btn btn-light w-100 fw-bold p-3 text-left">
                    <img src="{% static 'images/dashboard/icons/billings.png' %}" style="width:30px; height:30px; margin-right: 2rem;" />
                    Facturaciones
                  </a>
              </div>
              <div class="d-flex justify-content-left mb-2">
                  <a href="{% url 'sniper:my-payments' user.username %}" class="btn btn-light w-100 fw-bold p-3 text-left">
                    <img src="{% static 'images/dashboard/icons/time-left.png' %}" style="width:30px; height:30px; "/>
                    Historial de pagos
                  </a>
              </div>
              <div class="d-flex justify-content-left mb-2">
                  <a href="{% url 'users:update' %}" type="button" class="btn btn-light w-100 fw-bold p-3 text-left">
                    <img src="{% static 'images/dashboard/icons/settings.png' %}" style="width:30px; height:30px; margin-right: 1rem;"/>
                    Configuraciones
                  </a>
              </div>

            </div>
          </div>
          <div class="card mb-2 mb-lg-0">
            <div class="card-body p-2 align-middle mt-2">
              <!--<ul class="list-group list-group-flush rounded-3">
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fas fa-globe fa-lg text-warning"></i>
                  <p class="mb-0">NIT : {{ object.nit }}</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                  <p class="mb-0">Phone : {{ object.phone }}</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                  <p class="mb-0">Contact email : {{ object.contact }} </p>
                </li>-->
                <!--<li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                  <p class="mb-0">Attribute</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                  <p class="mb-0">Attribute</p>
                </li>
              </ul>-->
              <div class="d-flex justify-content-left mb-2">
                  <a href="{% url 'account_logout' %}" type="button" class="btn btn-light w-100 fw-bold p-3 text-left">
                    <img src="{% static 'images/dashboard/icons/log-out.png' %}" style="width:30px; height:30px; margin-right:10px;" class="p-1"/>
                    Cerrar sesión
                  </a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-9">
          {% block container %}
          <div class="card mb-4">
            <div class="card-body" style="display:flex; flex-direction:row; flex-wrap:wrap;">
              {% for project in object.project.all %}
                 <a href="{% url 'sniper:project-detail' project.id %}" style="text-decoration:none; width:350px; height:450px;">

                    <div class="profile-card-6" style="height:400px;"><img src="{{ project.image.url }}" class="img img-responsive img-center" style="object-fit:cover;">
                        <div class="profile-name">{{ project.name }}
                            <br>$ {{ project.price }} USD
                        </div>
                        <div class="profile-position">Bonos : {{ project.number_of_nfts }}</div>
                        <div class="profile-overview">
                            <div class="profile-overview">
                                  <div class="row text-center">
                                      <!--<div class="col-xs-4">
                                          <h3>1</h3>
                                          <p>Rank</p>
                                      </div>-->
                                      <!--<div class="col-xs-4">
                                          <h3>{{ project.chain }}</h3>
                                          <p>Blockchain</p>
                                      </div>
                                      <div class="col-xs-4">
                                          <h3>35</h3>
                                          <p>Goals</p>
                                      </div>-->
                                  </div>
                            </div>
                        </div>
                    </div>
                 </a>
              {% endfor %}
              <!--<div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">example@example.com</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">(097) 234-5678</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Mobile</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">(098) 765-4321</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>
                </div>
              </div>-->
            </div>
          </div>
          <!--<div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>-->
          {% endblock %}
        </div>
      </div>
    </div>
  </section>-->

{% endblock content %}

djsniper/templates/users/password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

djsniper/templates/users/show_voucher.html
{% extends "users/dashboard.html" %}
{% load static %}
{% load humanize %}
{% block title %}User: {{ object.username }}{% endblock %}
{% load crispy_forms_tags %}


{% block container %}
            <div class="card mb-4">
              <div class="card-body">
                <div class="row align-left">
                  <a href="{% url 'sniper:my-billings' user.username %}" class="m-2 mb-3 fw-bold text-black" style="text-decoration:none;">
                    <img src="{% static 'images/dashboard/icons/arrow.png' %}" style="width:32px; height:32px;" />
                    volver
                  </a>
                  <img src="{{ object.voucher.url }}">
                </div>

              </div>
            </div>
{% endblock %}