config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path("", include("djsniper.sniper.urls", namespace="sniper")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("djsniper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djsniper/sniper/urls.py
from django.urls import path, include
from . import views

app_name = "sniper"

urlpatterns = [
    path("", views.HomeCategoriesListView.as_view(), name="home"),
    path("projects/", views.ProjectListView.as_view(), name="projects"),
    path("create/", views.ProjectCreateView.as_view(), name="project-create"),
    path("project/<pk>/", views.ProjectDetailView.as_view(), name="project-detail"),
    path(
        "project/<pk>/update/", views.ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "project/<pk>/delete/", views.ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("project/<pk>/clear/", views.ProjectClearView.as_view(), name="project-clear"),
    path("project/<pk>/fetch-nfts/", views.FetchNFTsView.as_view(), name="fetch-nfts"),
    #path("project/<pk>/order/", views.ProjectDetailView.as_view(), name="order"),},
    path("my-projects/<str:username>/", views.UserProjectsView.as_view(), name="my-projects"),
    path("my-payments/<str:username>/", views.UserPaymentsHistoryView.as_view(), name="my-payments"),
    path("my-billings/<str:username>/", views.UserBillingsView.as_view(), name="my-billings"),
    path("add-voucher/<pk>/", views.OrderUpdateView.as_view(), name="add-voucher"),
    path("show-voucher/<pk>/", views.VoucherDetailView.as_view(), name="show-voucher"),
    path("choose/", views.ChooseRole, name="choose")

]

djsniper/users/urls.py
from django.urls import path

from djsniper.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    UserPersonalCreateView,
    UserEnterpriseCreateView,
    OrderCreateView,
    UserProfileView,
    user_password_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>", view=user_detail_view, name="detail"),
    path("profile/<str:username>", view=UserProfileView, name="profile"),
    path("personal/", view=UserPersonalCreateView.as_view, name="personal"),
    path("enterprise/", view=UserEnterpriseCreateView.as_view(), name="enterprise"),
    path("password/<str:username>", view=user_password_view, name="password")
]

djsniper/sniper/models.py
from django.db import models
from django.db.models import CharField
import uuid




class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    image = models.ImageField(null=True)
    created = models.DateField(auto_now_add=True)
    edited = models.DateField(auto_now=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return f"{self.name}"

class NFTProject(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    contract_address = models.CharField(max_length=100)
    contract_abi = models.TextField()
    name = models.CharField(max_length=50)  # e.g BAYC
    number_of_nfts = models.PositiveIntegerField(default=10)
    image = models.ImageField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True)
    supply = models.IntegerField(blank=True)
    price = models.CharField(max_length=200, null=True)
    chain = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=500, null=True)
    coin = CharField(max_length=20, default="USD", blank=False, editable=False)

    def __str__(self):
        return self.name


class NFT(models.Model):
    project = models.ForeignKey(
        NFTProject, on_delete=models.CASCADE, related_name="nfts"
    )
    rarity_score = models.FloatField(null=True)
    nft_id = models.PositiveIntegerField()
    image = models.ImageField(null=True)
    rank = models.PositiveIntegerField(null=True)

    def __str__(self):
        return f"{self.project.name}: {self.nft_id}"


class NFTAttribute(models.Model):
    project = models.ForeignKey(
        NFTProject, on_delete=models.CASCADE, related_name="attributes"
    )
    name = models.CharField(max_length=50)
    value = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name}: {self.value}"


class NFTTrait(models.Model):
    nft = models.ForeignKey(
        NFT, on_delete=models.CASCADE, related_name="nft_attributes"
    )
    attribute = models.ForeignKey(
        NFTAttribute, on_delete=models.CASCADE, related_name="traits"
    )
    rarity_score = models.FloatField(null=True)

    def __str__(self) -> str:
        return f"{self.attribute.name}: {self.attribute}"

djsniper/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField, ImageField, DateField, AutoField, ManyToManyField, BooleanField, \
    ForeignKey, \
    PROTECT
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from djsniper.sniper.models import NFTProject
from django.db import models
import uuid

Role = (
    ('Persona Natural', 'Persona Natural'),
    ('Empresa', 'Empresa'),
    ('Administrador', 'Administrador'),
    ('Desarrollador', 'Desarrollador')
)


class User(AbstractUser):
    """Default user for djsniper."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = CharField(max_length=30, null=True, blank=True)
    last_name = CharField(max_length=30, null=True, blank=True)
    nit = CharField(max_length=30, null=True)
    image = ImageField(blank=True, null=True, upload_to='images/userimage')
    edited = DateField(auto_now=True)
    allowed = BooleanField(default=False)
    project = ManyToManyField(NFTProject)
    role = CharField(max_length=20, choices=Role, default="Persona Natural", blank=True, editable=True)
    phone = CharField(max_length=30, null=True)
    contact = CharField(max_length=50, null=True)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

class Order(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    created = models.DateField(auto_now_add=True)
    edited = models.DateField(auto_now=True)
    nft = models.ForeignKey(NFTProject, on_delete=models.CASCADE, related_name="nft")
    purchase = models.CharField(max_length=200, null=True)
    bonuses = models.IntegerField(blank=True)
    voucher = ImageField(blank=True, null=True, upload_to='images/voucher')
    approved = BooleanField(default=False)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer")

djsniper/sniper/forms.py
from django import forms
from .models import NFTProject, Category


class ProjectForm(forms.ModelForm):
    class Meta:
        model = NFTProject
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ConfirmForm(forms.Form):
    hidden = forms.HiddenInput()

djsniper/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from .models import User, Order
from django import forms


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        fields = ["name", "first_name", "last_name", "image", "phone"]


class UserChangePassword(admin_forms.PasswordChangeForm):
    class Meta(admin_forms.PasswordChangeForm):
        model = User
        fields = '__all__'


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = '__all__'
        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserPersonalCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ["username", "name", "first_name", "last_name", "nit", "phone", "contact", "email"]


class UserEnterpriseCreationForm(admin_forms.UserCreationForm):
    # role = forms.CharField(widget=forms.CharField(attrs={"value":"Empresa"}))

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ["username", "name", "nit", "phone", "contact", "email", "role"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].widget.attrs.update({"value": "Empresa", "class": "invisible", "type": "hidden"})
        self.fields['role'] = forms.CharField(widget=forms.HiddenInput())


class OrderCreationForm(forms.ModelForm):
    class Meta(forms.Form):
        model = Order
        fields = ["id", "nft", "bonuses", "buyer"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # self.fields["nft"].widget.attrs.update({"class": "invisible", "type": "hidden"})
        # self.fields["nft"] = forms.IntegerField(widget=forms.HiddenInput())
        # self.fields["buyer"].widget.attrs.update({"class": "invisible", "type": "hidden"})
        # self.fields["buyer"] = forms.IntegerField(widget=forms.HiddenInput())
        # self.fields["buyer"].widget.attrs.update({"value" : request.user , "class" : "invisible", "type" : "hidden "})


class OrderUpdateForm(forms.ModelForm):
    class Meta(forms.Form):
        model = Order
        fields = ["nft", "purchase", "bonuses", "buyer", "voucher"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["nft"].widget.attrs.update({'readonly': 'readonly'})

djsniper/sniper/api/views.py
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.viewsets import GenericViewSet
from djsniper.sniper.models import NFTProject
from .serializers import NFTProjectSerializer, CategorySerializer


class ProjectViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = NFTProjectSerializer
    queryset = NFTProject.objects.all()
    lookup_field = "name"


class CategoryViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = CategorySerializer
    queryset = CategorySerializer.objects.all()
    lookup_field = "name"

djsniper/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

djsniper/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django.views.generic import DetailView, RedirectView, UpdateView
from .models import User, Order
from .forms import UserPersonalCreationForm, UserEnterpriseCreationForm, UserChangeForm, UserChangePassword
from django import forms


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/dashboard.html"


user_detail_view = UserDetailView.as_view()


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/user_detail.html"


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserPasswordUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserChangePassword
    template_name = "users/password.html"


user_password_view = UserPasswordUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={
            "username": self.request.user.username
        })


user_redirect_view = UserRedirectView.as_view()


class UserPersonalCreateView(generic.CreateView):
    template_name = "account/signup_personal.html"

    # model = User
    form_class = UserPersonalCreationForm

    def form_valid(self, form):
        instance = form.save()
        return redirect("sniper:home")


Role = (
    ('Persona Natural', 'Persona Natural'),
    ('Empresa', 'Empresa'),
    ('Administrador', 'Administrador'),
    ('Desarrollador', 'Desarrollador')
)


class UserEnterpriseCreateView(generic.CreateView):
    template_name = "account/signup_enterprise.html"
    form_class = UserEnterpriseCreationForm
    # model = User
    success_message = _("Informaton successfully updated")
    initial = {
        "role": "Empresa"
    }

    def form_valid(self, form):
        instance = form.save()
        return redirect("sniper:home")


class OrderCreateView(generic.CreateView):
    template_name = "sniper/order_create.html"
    form_class = Order
    success_message = _("Tu orden ha sido listada")

djsniper/templates/sniper/project_clear.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-xl mx-auto">
    <div class="border-b border-gray-200 py-5">
        <h1 class="text-3xl font-bold leading-tight text-gray-900">
            Clear Project Data
        </h1>
    </div>

    <div class="mt-3">
        <a href="{% url 'sniper:project-detail' object.id %}" class="text-blue-500 hover:text-blue-600">
            Go back to {{ object.name }}
        </a>
    </div>

    <form class="mt-3" method="post">
        {% csrf_token %}
        <button
            class="bg-red-200 text-red-600 hover:bg-red-200 hover:text-red-800 shadow rounded px-3 py-2">Submit</button>
    </form>

</div>

{% endblock content %}

djsniper/templates/sniper/project_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-xl mx-auto">
    <div class="border-b border-gray-200 py-5">
        <h1 class="text-3xl font-bold leading-tight text-gray-900">
            Delete Project
        </h1>
    </div>

    <div class="mt-3">
        <a href="{% url 'sniper:project-detail' object.id %}" class="text-blue-500 hover:text-blue-600">
            Go back to {{ object.name }}
        </a>
    </div>

    <form class="mt-3" method="post">
        {% csrf_token %}
        <button
            class="bg-red-200 text-red-600 hover:bg-red-200 hover:text-red-800 shadow rounded px-3 py-2">Submit</button>
    </form>

</div>

{% endblock content %}

djsniper/templates/sniper/project_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block content %}

<!--<div class="max-w-xl mx-auto">
    <div class="flex items-center justify-between border-b border-gray-200 py-5">
        <div>
            <h1 class="text-3xl font-bold leading-tight text-gray-900">
                {{ object.name }}
            </h1>
        </div>
        <div>
            <a href="?order=rank"
                class="bg-blue-200 text-blue-600 hover:bg-blue-200 hover:text-blue-800 shadow rounded px-3 py-2">
                Order
            </a>
        </div>
    </div>

    <div class="mt-5">
        <p>{{ object.number_of_nfts }} NFTs</p>
        <div class="mt-5 grid grid-cols-4 gap-4">
            {% for nft in nfts %}
            <div class="py-3 px-3 border border-gray-200 shadow-sm">
                <img class="w-full rounded-md" src="https://ipfs.io/ipfs/{{ nft.image_url }}" />
                <div class="mt-1">
                    <h1 class="text-lg text-gray-800 font-bold">#{{ nft.nft_id }}</h1>
                    <p class="text-base text-gray-600">Score: {{ nft.rarity_score|floatformat:2 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="py-10">
            <a href="{% url 'sniper:fetch-nfts' object.id %}"
                class="bg-green-200 text-green-600 hover:bg-green-200 hover:text-green-800 shadow rounded px-3 py-2">
                Fetch NFTs
            </a>
        </div>
    </div>

    <div class="mt-5">
        <a href="{% url 'sniper:project-clear' object.id %}"
            class="bg-gray-200 text-gray-600 hover:bg-gray-200 hover:text-gray-800 shadow rounded px-3 py-2">
            Clear NFT data
        </a>
        <a href="{% url 'sniper:project-update' object.id %}"
            class="ml-3 bg-blue-200 text-blue-600 hover:bg-blue-200 hover:text-blue-800 shadow rounded px-3 py-2">
            Update
        </a>
        <a href="{% url 'sniper:project-delete' object.id %}"
            class="ml-3 bg-red-200 text-red-600 hover:bg-red-200 hover:text-red-800 shadow rounded px-3 py-2">
            Delete
        </a>
    </div>
</div>-->
<section class="">
        <h2 class="text-center text-success m-5">DETALLES DEL PROYECTO</h2>
        <div class="container pt-1 align-center">

            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-3 mt-2">
                        <img class="card-img img-fluid" src="{{ object.image.url }}" alt="Card image cap" id="product-detail">
                    </div>
                    <!--<div class="row">

                        <div class="col-1 align-self-center">
                            <a href="{% url 'sniper:projects' %}" role="button" data-bs-slide="prev">
                                <i class="text-dark fas fa-chevron-left"></i>
                                <span class="sr-only">Previous</span>
                            </a>
                        </div>


                    </div>-->
                </div>
                <!-- col end -->
                <div class="col-lg-5">
                    <div class="card mb-3 mt-2 p-5">
                        <a href="{% url 'sniper:projects' %}" class="m-2 p-2 mb-3 fw-bold text-black" style="text-decoration:none;">
                          <img src="{% static 'images/dashboard/icons/arrow.png' %}" style="width:22px; height:22px;" />
                          Página anterior
                        </a>
                        <div class="card-body">
                            <h1 class="h2">{{ object.name }}</h1>
                            <p class="h5 py-2 text-primary">Precio por unidad : ${{object.price}} USD</p>
                            <p class="py-2">
                                <span class="list-inline-item text-dark">Categoría : {{ object.category.name }}</span>
                            </p>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <h6>Brand:</h6>
                                </li>
                                <li class="list-inline-item">
                                    <p class="text-muted"><strong>Easy Wear</strong></p>
                                </li>
                            </ul>

                            <h6>Descripción:</h6>
                            <p>{{ object.description }}</p>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <h6>Cantidad disponible: </h6>
                                </li>
                                <li class="list-inline-item">
                                    <p class="text-muted"><strong>{{ object.supply }}</strong></p>
                                </li>
                            </ul>

                            <!--<h6>Specification:</h6>
                            <ul class="list-unstyled pb-3">
                                <li>Lorem ipsum dolor sit</li>
                                <li>Amet, consectetur</li>
                                <li>Adipiscing elit,set</li>
                                <li>Duis aute irure</li>
                                <li>Ut enim ad minim</li>
                                <li>Dolore magna aliqua</li>
                                <li>Excepteur sint</li>
                            </ul>-->

                            <!--<form action="" method="GET">

                                <input type="hidden" name="product-title" value="Activewear">
                                <div class="row">
                                    --<div class="col-auto">
                                        <ul class="list-inline pb-3">
                                            <li class="list-inline-item">Size :
                                                <input type="hidden" name="product-size" id="product-size" value="S">
                                            </li>
                                            <li class="list-inline-item"><span class="btn btn-success btn-size">S</span></li>
                                            <li class="list-inline-item"><span class="btn btn-success btn-size">M</span></li>
                                            <li class="list-inline-item"><span class="btn btn-success btn-size">L</span></li>
                                            <li class="list-inline-item"><span class="btn btn-success btn-size">XL</span></li>
                                        </ul>
                                    </div>--
                                    <div class="col-auto">
                                        <ul class="list-inline pb-3">
                                            <li class="list-inline-item text-right">
                                                Quantity
                                                <input type="hidden" name="product-quanity" id="product-quanity" value="1">
                                            </li>
                                            <li class="list-inline-item"><span class="btn btn-primary" id="btn-minus">-</span></li>
                                            <li class="list-inline-item"><span class="badge bg-secondary" id="var-value">1</span></li>
                                            <li class="list-inline-item"><span class="btn btn-primary" id="btn-plus">+</span></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="row pb-3">
                                    <div class="col d-grid">
                                        <button type="submit" class="btn btn-primary btn-lg" name="submit" value="buy">Comprar</button>
                                    </div>
                                    --<div class="col d-grid">
                                        <button type="submit" class="btn btn-success btn-lg" name="submit" value="addtocard">Add To Cart</button>
                                    </div>--
                                </div>
                            </form>-->
                          <form class="login" method="post">
                           {% csrf_token %}
                            <tr>
                              <th>
                                <label for="id_nft" style="display:none; visibility:hidden;" >Nft:</label>
                              </th>
                              <td>
                                <select name="nft" required id="id_nft"  value="{{object.id}}" style="display:none; visibility:hidden;">
                                  <option value="{{object.id}}" selected ></option>
                                </select>
                              </td>
                            </tr>
                            <tr>
                              <th>
                                <label for="id_bonuses"></label>
                              </th>
                              <td>
                                <input type="number" name="bonuses" id="id_bonuses">
                              </td>
                            </tr>
                            <tr>

                              <th>
                                <label for="id_buyer" style="display:none; visibility:hidden;">Buyer:</label>
                              </th>
                              <td>
                                <select name="buyer" value="{{ user.id }}" required id="id_buyer" style="display:none; visibility:hidden;">
                                <option value="{{ user.id }}" selected ></option>
                              </select>
                              </td>
                            </tr>
                            <tr>
                              <th>
                                <label for="id_purchase" style="display:none; visibility:hidden;" value="" >Purchase: </label>
                              </th>
                              <td>
                                <input name="purchase" type="number" id="id_purchase" style="display:none; visibility:hidden;">
                              </td>
                            </tr>

                            <button class="primaryAction btn btn-success btn-lg mb-2 mt-5" type="submit" style="width: 100%">Comprar</button>

                          </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Close Content -->

{% endblock %}

djsniper/templates/sniper/project_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/product-card.css' %}">
{% endblock %}
{% block content %}

<h1 class="text-3xl font-bold leading-tight text-gray-900 m-5">
    Projects
</h1>
<div class="container text-center" style="display:flex; flex-direction:row; justify-content:space-between; flex-wrap:wrap; align-items:center;">

{% for project in object_list %}

        <a href="{% url 'sniper:project-detail' project.id %}" style="text-decoration:none; width:350px; height:450px;">

            <div class="profile-card-6" style="height:400px;"><img src="{{ project.image.url }}" class="img img-responsive img-center" style="object-fit:cover;">
                <div class="profile-name">{{ project.name }}
                    <br>$ {{ project.price }} USD
                </div>
                <div class="profile-position">Bonos : {{ project.number_of_nfts }}</div>
                <div class="profile-overview">
                    <div class="profile-overview">
                          <div class="row text-center">
                              <!--<div class="col-xs-4">
                                  <h3>1</h3>
                                  <p>Rank</p>
                              </div>-->
                              <!--<div class="col-xs-4">
                                  <h3>{{ project.chain }}</h3>
                                  <p>Blockchain</p>
                              </div>
                              <div class="col-xs-4">
                                  <h3>35</h3>
                                  <p>Goals</p>
                              </div>-->
                          </div>
                    </div>
                </div>
            </div>
        </a>
{% endfor %}

</div>
{% endblock content %}

djsniper/templates/sniper/project_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-xl mx-auto">
    <h1 class="text-3xl font-bold leading-tight text-gray-900">
        Update {{ object.name }}
    </h1>

    <div class="mt-3">
        <a href="{% url 'sniper:project-detail' object.id %}" class="text-blue-500 hover:text-blue-600">
            Go back to {{ object.name }}
        </a>
    </div>

    <form class="mt-3" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button
            class="bg-gray-200 text-gray-600 hover:bg-gray-200 hover:text-gray-800 shadow rounded px-3 py-2">Submit</button>
    </form>
</div>

{% endblock content %}